on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Set compiler version
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo ln -sf /usr/bin/g++-10 /usr/local/sbin/g++
        sudo ln -sf /usr/bin/gcc-10 /usr/local/sbin/gcc
        g++ --version
        gcc --version
    - name: Install dependencies (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libprotobuf-dev
    - name: Install dependencies (macos-latest)
      if: matrix.os == 'macos-latest'
      run: |
        brew install protobuf
    - name: Initialize Java
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build agent
      run: |
        gradle --no-daemon assembleRelease
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-x86_64
        path: com.sandpolis.agent.nano/build/exe/main/release/stripped/com.sandpolis.agent.nano
