on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - name: Set compiler version
      run: |
        sudo ln -sf /usr/bin/g++-10 /usr/local/sbin/g++
        sudo ln -sf /usr/bin/gcc-10 /usr/local/sbin/gcc
        g++ --version
        gcc --version
    - name: Install dependencies
      run: |
        sudo apt-get install libncursesw5-dev libprotobuf-dev
    - name: Initialize Java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Checkout root repository
      uses: actions/checkout@v2
      with:
        repository: sandpolis/sandpolis
    - name: Checkout submodules
      run: |
        git submodule update --init --remote --merge com.sandpolis.agent.micro
    - name: Execute build
      run: |
        gradle --no-daemon :com.sandpolis.agent.micro:assembleRelease
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: com.sandpolis.agent.micro/build/exe/main/release/stripped/com.sandpolis.agent.micro
